[[language]]
name = "rust"
indent = { tab-width = 2, unit = "  "}
auto-format = true

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "python"
comment-token = "#"
indent = { tab-width = 4, unit = "     "}
language-server = { command = "pylsp" }
auto-format = true
